baseURL = "https://unibo-oop.github.io/showcase/"
languageCode = "en-us"
title = "OOP Projects showcase"
Paginate = 1000
googleAnalytics = ""
theme = "showcase"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

# this setting should always be set to false, otherwise it will break the section navigation bar
pluralizelisttitles = false

[params]
  author = "Showcase of \"Programmazione ad Oggetti\" @ UniBo / Cesena"
  description = "OOP Projects that looked good. Note: they may be not well-engineered"
  message = "OOP Projects that looked good. IMPORTANT NOTE: they may be not well-engineered! Use for fun, not as a basis for finding good projects (intended as \"projects that scored a good grade at the exam\")."
  hideAutoMenu = false

  # Pagination options
  paginate = 30
  multipage = true

  # Dark mode
  darkMode = true

# [[menu.main]]
#   name = "External"
#   url = "https://danysk.github.io/"

# [social]
#   facebook = "https://facebook.com"
#   twitter = "https://twitter.com"
#   instagram = "https://instagram.com"
#   linkedin = "https://linkedin.com"
